### PR TITLE
WIP Create a top-level span for events which have no actor

### PR DESCRIPTION
**Pull request by vrutkovs**
If no actor can be found for the event, set it to object itself. This would ensure events created by operators (i.e. new pods) can be traced properly.
In order to structure this correctly actor == object in objRef and this case takes precendence over ownership check. 

This also updates `createTraceFromTopLevelObject`: 
* use `status` update time instead of `spec`, so that pod started event would be have valid timestamps.
* allow redefining `component` so that it could be set from event source instead of managedFields.

Not entirely sure how to reproduce this - in Openshift this can be reproduced by using `oc debug node/` which creates a priviledged pod on the node. I think any `kubectl create pod` would replicate this behaviour.

Before:
Screenshot_2021-03-26 Jaeger UI

After:
Screenshot_2021-03-26 Jaeger UI(2)

### CODE REVIEW

**Comment by vrutkovs** [comment]
Marking as WIP as it fails existing tests

**Comment by bboreham** [comment]
Interesting thought, thanks.
It is a bit of a problem dealing with a "big bag of heuristics" that you tweak one thing and another thing breaks.

Do you think you could add a test (source events and expected output) for the new behaviour you are adding?

**Comment by vrutkovs** [comment]
>Do you think you could add a test (source events and expected output) for the new behaviour you are adding?

yup, will do

**Comment by thundering-herd** [comment]
@vrutkovs is this PR still active?

**Comment by vrutkovs** [comment]
Sorry, this needed quite a few changes in events we emit, so I dropped this.

Feel free to pick up of course

**Pull request closed without merging**
